// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package ssf.sample



object SampleProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq(
    ssf.sample.SSFSample,
    ssf.sample.SSFSpan
  )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChBzc2Yvc2FtcGxlLnByb3RvEgNzc2Yi5wMKCVNTRlNhbXBsZRItCgZtZXRyaWMYASABKA4yFS5zc2YuU1NGU2FtcGxlLk1ld
  HJpY1IGbWV0cmljEhIKBG5hbWUYAiABKAlSBG5hbWUSFAoFdmFsdWUYAyABKAJSBXZhbHVlEhwKCXRpbWVzdGFtcBgEIAEoA1IJd
  GltZXN0YW1wEhgKB21lc3NhZ2UYBSABKAlSB21lc3NhZ2USLQoGc3RhdHVzGAYgASgOMhUuc3NmLlNTRlNhbXBsZS5TdGF0dXNSB
  nN0YXR1cxIfCgtzYW1wbGVfcmF0ZRgHIAEoAlIKc2FtcGxlUmF0ZRIsCgR0YWdzGAggAygLMhguc3NmLlNTRlNhbXBsZS5UYWdzR
  W50cnlSBHRhZ3MSEgoEdW5pdBgJIAEoCVIEdW5pdBo3CglUYWdzRW50cnkSEAoDa2V5GAEgASgJUgNrZXkSFAoFdmFsdWUYAiABK
  AlSBXZhbHVlOgI4ASJECgZNZXRyaWMSCwoHQ09VTlRFUhAAEgkKBUdBVUdFEAESDQoJSElTVE9HUkFNEAISBwoDU0VUEAMSCgoGU
  1RBVFVTEAQiOAoGU3RhdHVzEgYKAk9LEAASCwoHV0FSTklORxABEgwKCENSSVRJQ0FMEAISCwoHVU5LTk9XThADIrADCgdTU0ZTc
  GFuEhgKB3ZlcnNpb24YASABKAVSB3ZlcnNpb24SGQoIdHJhY2VfaWQYAiABKANSB3RyYWNlSWQSDgoCaWQYAyABKANSAmlkEhsKC
  XBhcmVudF9pZBgEIAEoA1IIcGFyZW50SWQSJwoPc3RhcnRfdGltZXN0YW1wGAUgASgDUg5zdGFydFRpbWVzdGFtcBIjCg1lbmRfd
  GltZXN0YW1wGAYgASgDUgxlbmRUaW1lc3RhbXASFAoFZXJyb3IYByABKAhSBWVycm9yEhgKB3NlcnZpY2UYCCABKAlSB3NlcnZpY
  2USKAoHbWV0cmljcxgKIAMoCzIOLnNzZi5TU0ZTYW1wbGVSB21ldHJpY3MSKgoEdGFncxgLIAMoCzIWLnNzZi5TU0ZTcGFuLlRhZ
  3NFbnRyeVIEdGFncxIcCglpbmRpY2F0b3IYDCABKAhSCWluZGljYXRvchISCgRuYW1lGA0gASgJUgRuYW1lGjcKCVRhZ3NFbnRye
  RIQCgNrZXkYASABKAlSA2tleRIUCgV2YWx1ZRgCIAEoCVIFdmFsdWU6AjgBSgQICRAKYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}